name: Template repository setup

# The workflow will run when the "Use this template" button is used
on:
  push:

jobs:
  setup-template:
    # We only run this action when the repository isn't the template repository
    if: ${{ !github.event.repository.is_template }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Make rename script executable
        run: chmod +x ./.github/scripts/rename.sh

      - name: Update package.json
        env:
          GITHUB_REPOSITORY_DESCRIPTION: ${{ github.event.repository.description }}
        run:
          ./.github/scripts/rename.sh "${{ github.repository }}" "${{ github.repository_owner }}" "$GITHUB_REPOSITORY_DESCRIPTION"

      - name: Add rename summary
        run: |
          echo "## Rename result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: 'Remove files not needed in the user''s copy of the template'
        run: |
          rm -f "./.github/scripts/rename.sh"
          rm -f "./.github/workflows/template-setup.yml"

      - name: Add remove summary
        run: |
          echo "## Remove result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Update commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: initial commit'
          commit_options: --amend
          push_options: --force
          skip_fetch: true

      - name: Add commit summary
        run: |
          echo "## Commit result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
